-- Add missing fields to einkommensteuerbescheide table based on real document analysis
ALTER TABLE public.einkommensteuerbescheide
ADD COLUMN steuer_id_nummer TEXT,
ADD COLUMN finanzamt_name TEXT,
ADD COLUMN finanzamt_adresse TEXT,
ADD COLUMN bescheiddatum DATE,
ADD COLUMN solidaritaetszuschlag TEXT,
ADD COLUMN gemeinsame_veranlagung BOOLEAN DEFAULT false,
ADD COLUMN steuerabzug_vom_lohn TEXT,
ADD COLUMN verbleibende_steuer TEXT,
ADD COLUMN summe_der_einkuenfte TEXT,
ADD COLUMN gesamtbetrag_der_einkuenfte TEXT,
ADD COLUMN sonderausgaben TEXT,
ADD COLUMN altersvorsorgeaufwendungen TEXT,
ADD COLUMN krankenversicherung TEXT,
ADD COLUMN pflegeversicherung TEXT,
ADD COLUMN einkuenfte_selbstaendig TEXT,
ADD COLUMN einkuenfte_nichtselbstaendig TEXT,
ADD COLUMN bruttoarbeitslohn TEXT,
ADD COLUMN werbungskosten TEXT,
ADD COLUMN vorauszahlungen TEXT;